#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Short-Description: Socket server running on port 9000
# Description:       Socket server running on port 9000 for aesd assignment 5 part 2
### END INIT INFO

set -e

DAEMON=/usr/bin/aesdsocket
NAME=aesdsocket
DESC="aesdsocket server"

# exit if daemon is not executable
test -x $DAEMON || exit 0

start_it_up()
{
  echo "Starting $DESC"
  start-stop-daemon --start --verbose --name $NAME --exec $DAEMON -- -d
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

shut_it_down()
{
  echo "Stopping $DESC"
  start-stop-daemon --stop --verbose --oknodo --name $NAME
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
  start)
    start_it_up
  ;;
  stop)
    shut_it_down
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop}" >&2
    exit 2
  ;;
esac
